/* Static prototype: role simulation is not an authorization boundary. */
'use strict';
const KEY='seamolec-fydp-demo-v1';
const seed=window.SEAMOLEC_DATA;
let db=structuredClone(seed),storageWarning=false;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===1)db=saved;}catch{storageWarning=true;}
const qs=new URLSearchParams(location.search);
const page=location.pathname.split('/').pop()?.replace('.html','')||'index';
let actor=null;
try{actor=db.users.find(u=>u.id===sessionStorage.getItem('seamolec-actor'))||null;}catch{}
let period=qs.get('period')||db.periods[0].id,year=qs.get('year')||'all';
if(!db.periods.some(p=>p.id===period))period=db.periods[0].id;
let search='',division='',status='',currentPage=1,docType='',docScope=qs.get('program')||'',docSort='newest',docComponent=qs.get('component')||'';
let section=qs.get('tab')||'components',adminTab=qs.get('tab')||'programs';
const main=document.querySelector('#main');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID();
const uniq=a=>[...new Set(a)];
const byPeriod=a=>a.filter(x=>x.period===period);
const activePeriod=()=>db.periods.find(p=>p.id===period);
const years=()=>Array.from({length:activePeriod().end-activePeriod().start+1},(_,i)=>activePeriod().start+i);
const role=()=>actor?.role;
const canUpload=()=>role()==='admin'||role()==='staf';
const canEdit=p=>role()==='admin'||(role()==='staf'&&actor.programs.includes(p));
const link=(path,params={})=>`${path}.html?${new URLSearchParams({period,year,...params})}`;
const opt=(value,label,selected)=>`<option value="${esc(value)}" ${String(value)===String(selected)?'selected':''}>${esc(label)}</option>`;
const options=(values,selected)=>values.map(v=>opt(v,v,selected)).join('');
const badge=s=>`<span class="badge ${s==='Perlu perhatian'?'attention':s==='Selesai'||s==='On track'?'running':'planned'}">${esc(s)}</span>`;
const statuses=['Belum ada data','Belum mulai','On track','Perlu perhatian','Selesai','Ditunda'];
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));return true;}catch{toast('Penyimpanan browser tidak tersedia atau penuh. Perubahan hanya bertahan selama halaman ini terbuka.');return false;}}
function toast(s){document.querySelector('#toast').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>document.querySelector('#toast').textContent='',7000);}
function empty(title,text,action=''){return `<div class="empty-state"><h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;}
function heading(title,desc='',action=''){return `<div class="heading title-top"><div class="intro"><p class="eyebrow">${esc(activePeriod().name)}</p><h1>${esc(title)}</h1>${desc?`<p class="lead">${esc(desc)}</p>`:''}</div>${action?`<div class="actions">${action}</div>`:''}</div>`;}
function scopeTools(extra=''){return `<div class="toolbar"><label>Periode FYDP<select class="field" id="period">${db.periods.map(p=>opt(p.id,p.name,period)).join('')}</select></label><label>Tahun rencana<select class="field" id="year">${opt('all','Seluruh tahun',year)}${options(years(),year)}</select></label>${extra}</div>`;}
function searchField(placeholder='Cari flagship, komponen, atau aktivitas'){return `<label class="grow">Pencarian<input class="field" id="search" type="search" placeholder="${placeholder}" value="${esc(search)}"></label>`;}
function header(){document.querySelector('#header').innerHTML=`<a class="brand" href="${link('index')}">SEAMOLEC</a><nav class="nav" aria-label="Navigasi utama">${[['index','Beranda'],['programs','Flagship'],['kpi','KPI'],['knowledge','Pustaka']].map(([p,t])=>`<a href="${link(p)}" ${page===p?'aria-current="page"':''}>${t}</a>`).join('')}${role()==='admin'?`<a href="${link('admin')}" ${page==='admin'?'aria-current="page"':''}>Admin</a>`:''}</nav><a class="account-link" href="${link('login')}">${actor?esc(actor.name)+' · '+esc(actor.role):'Masuk'}</a>`;}
function banner(){return `<div class="demo-banner"><span><strong>Prototipe</strong> · ${actor?`Pratinjau ${esc(actor.role)}. Perubahan hanya tersimpan di browser ini.`:'Data rencana FYDP. Masuk ke mode demo untuk mencoba pengelolaan.'}</span>${actor?'<button data-action="logout">Keluar demo</button>':`<a class="text-link" href="${link('login')}">Coba peran →</a>`}</div>${storageWarning?'<p class="form-note">Data lokal tidak dapat dibaca. Menampilkan data awal.</p>':''}`;}
function activitiesFor(p){return byPeriod(db.activities).filter(a=>a.program===p&&(year==='all'||String(a.year)===year));}
function completion(list){const known=list.filter(a=>a.status!=='Belum ada data');return !list.length||known.length!==list.length?null:Math.round(list.filter(a=>a.status==='Selesai').length/list.length*100);}
function progress(list){const n=completion(list);return n===null?'<div class="empty-progress">Capaian belum lengkap</div>':`<div class="progress"><progress value="${n}" max="100" aria-label="Aktivitas selesai ${n}%"></progress><span>${n}%</span></div>`;}
function programList(){let ps=byPeriod(db.programs).filter(p=>!division||p.division===division);return ps.filter(p=>{const all=activitiesFor(p.id);const text=[p.name,p.title,p.cluster,p.division,...all.map(a=>a.name),...db.components.filter(c=>c.program===p.id&&(year==='all'||all.some(a=>a.component===c.id))).map(c=>c.name)].join(' ').toLowerCase();return text.includes(search.toLowerCase())&&(year==='all'||all.length)&&(!status||all.some(a=>a.status===status));});}
function programCard(p){const aa=activitiesFor(p.id);return `<a class="program-card" href="${link('program',{id:p.id})}"><span class="badge planned">${esc(p.division)} · ${esc(p.strategy)}</span><h3>${esc(p.name)}</h3><p class="short-title">${esc(p.title)}</p>${progress(aa)}<div class="card-bottom"><span>${aa.length} aktivitas${year==='all'?'':` · ${year}`}</span><span aria-hidden="true">↗</span></div></a>`;}
function programTools(){return scopeTools(searchField()+`<label>Divisi utama<select id="division" class="field">${opt('','Semua divisi',division)}${options(uniq(byPeriod(db.programs).map(p=>p.division)),division)}</select></label>${page==='programs'?`<label>Status aktivitas<select id="status" class="field">${opt('','Semua status',status)}${options(statuses,status)}</select></label>`:''}`);}
function renderPrograms(home){const ps=programList(),size=home?3:6,total=Math.max(1,Math.ceil(ps.length/size));currentPage=Math.min(currentPage,total);const visible=ps.slice((currentPage-1)*size,currentPage*size);return heading(home?'Program kerja':'Semua flagship',home?'Satu ruang untuk melihat rencana, aktivitas, dan capaian SEAMOLEC.':'Telusuri flagship, lalu buka komponen dan aktivitas di dalamnya.',home?`<a class="button secondary" href="${link('programs')}">Lihat semua flagship</a>`:'')+programTools()+(home?`<div class="summary-strip"><div><strong>${byPeriod(db.programs).length}</strong><span>flagship</span></div><div><strong>${byPeriod(db.components).length}</strong><span>komponen</span></div><div><strong>${byPeriod(db.activities).filter(a=>year==='all'||String(a.year)===year).length}</strong><span>aktivitas ${year==='all'?'rencana':year}</span></div><a class="text-link" href="${link('divisions')}">Rencana per divisi →</a></div>`:'')+`<p class="result-count" role="status">${ps.length} flagship ditemukan${year!=='all'?` untuk ${year}`:''}</p>`+(ps.length?`<div class="cards">${visible.map(programCard).join('')}</div><nav class="pagination" aria-label="Halaman flagship"><button data-page="${currentPage-1}" ${currentPage===1?'disabled':''} aria-label="Halaman sebelumnya">←</button><span>${currentPage} / ${total}</span><button data-page="${currentPage+1}" ${currentPage===total?'disabled':''} aria-label="Halaman berikutnya">→</button></nav>`:empty('Tidak ada hasil','Coba kata kunci, tahun, atau divisi lain.'))+(home?`<div class="lower"><section><div class="section-heading"><h2>Tonggak periode</h2><a class="text-link" href="${link('milestones')}">Lihat semua →</a></div>${byPeriod(db.milestones).filter(m=>year==='all'||String(m.year)===year).slice(0,2).map(m=>`<a class="simple-row" href="${link('milestones')}"><span>${esc(m.name.split(';')[0])}</span><time>${m.year}</time></a>`).join('')||'<p class="muted">Belum ada milestone untuk periode ini.</p>'}</section><section><div class="section-heading"><h2>Pustaka pengetahuan</h2><a class="text-link" href="${link('knowledge')}">Buka pustaka →</a></div><p class="quiet-note">Simpan pedoman umum, dokumen komponen, dan bukti realisasi di tempat yang sesuai. Berkas sumber belum dipublikasikan.</p>${canUpload()?`<a class="button secondary" href="${link('upload')}">Unggah dokumen demo</a>`:''}</section></div>`:'')+`<p class="quiet-note">Persentase dihitung dari aktivitas selesai, hanya jika seluruh status sudah diisi. Capaian aktivitas berbeda dari capaian KPI. <a class="link-underline" href="sources.html">Baca catatan sumber.</a></p>`;}
function tabs(items,active,base,params={}){return `<nav class="tabs" aria-label="Bagian halaman">${items.map(([key,label])=>`<a href="${link(base,{...params,tab:key})}" ${key===active?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;}
function renderDetail(){const p=db.programs.find(p=>p.id===qs.get('id')&&p.period===period);if(!p)return empty('Pilih flagship','Buka salah satu flagship untuk melihat komponen dan aktivitasnya.',`<a class="button" href="${link('programs')}">Lihat flagship</a>`);const aa=activitiesFor(p.id);let out=`<a class="backlink" href="${link('programs')}">← Semua flagship</a><div class="section-space">${heading(p.name,p.title)}<div class="label-list"><span>${esc(p.cluster)}</span><span>Strategi ${esc(p.strategy)}</span><span>Lead: ${esc(p.division)} (indikatif)</span></div></div>${scopeTools()}${tabs([['components','Komponen & aktivitas'],['kpi','KPI terkait'],['documents','Dokumen'],['about','Tentang flagship']],section,'program',{id:p.id})}`;
if(section==='kpi')return out+renderKpis(p.id,false);
if(section==='documents')return out+renderLibrary(p.id,false);
if(section==='about'){const f=db.funding.find(f=>f['Flagship / Aset']===p.id);return out+`<div class="source-block"><h2>Penanggung jawab & strategi</h2><p>${esc(p.team)} · ${esc(p.strategy)}</p><p class="quiet-note">Pemetaan lead division dari workbook bersifat indikatif dan perlu penetapan resmi.</p><p>${esc(p.source)}</p></div>${f?`<div class="source-block"><h2>Rencana sumber pendanaan</h2><p>${esc(f['Sumber Dana Utama'])}</p><p class="muted">${esc(f.Rasional)}</p></div>`:''}`;}
const comps=byPeriod(db.components).filter(c=>c.program===p.id&&(year==='all'||aa.some(a=>a.component===c.id)));
out+=`<div class="section-heading"><h2>${comps.length} komponen</h2><span class="muted">${aa.length} aktivitas</span></div><p class="quiet-note">Buka satu komponen untuk melihat kegiatan, tahun rencana, PIC, dan statusnya.</p>`;
return out+(comps.map(c=>`<details class="component" ${qs.get('component')===c.id?'open':''}><summary><div><h3>${esc(c.name)}</h3><small>${aa.filter(a=>a.component===c.id).length} aktivitas</small></div></summary>${aa.filter(a=>a.component===c.id).map(a=>`<article class="activity-item"><div><h4>${esc(a.name)}</h4><p>${esc(a.code)} · ${a.year} · ${esc(a.division)}</p><p>PIC: ${esc(a.pic||'Belum ditetapkan')}</p>${a.notes?`<p>${esc(a.notes)}</p>`:''}<small class="muted">${esc(a.source||'Input demo')}</small></div><div>${badge(a.status)}${canEdit(p.id)?`<p><button class="plain-button" data-edit="activities" data-id="${esc(a.id)}">Perbarui aktivitas</button></p>`:''}</div></article>`).join('')}<div class="activity-item"><a class="text-link" href="${link('knowledge',{program:p.id,component:c.id})}">Dokumen komponen →</a></div></details>`).join('')||empty('Belum ada aktivitas','Pilih tahun lain atau tambahkan komponen melalui admin.'));}
function formatValue(n,unit){return n===null||n===undefined||n===''?'—':`${new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(unit.startsWith('%')?n*100:n)}${unit.startsWith('%')?'%':''}`;}
function attainment(actual,target){return actual===null||actual===undefined||target===null||target===undefined||target<=0?null:Math.round(actual/target*100);}
function renderKpis(program=null,withHeading=true){const y=year==='all'?String(activePeriod().end):year;const kk=byPeriod(db.kpis).filter(k=>(!program||k.programs.includes(program))&&`${k.name} ${k.category} ${k.programs.join(' ')}`.toLowerCase().includes(search.toLowerCase()));return (withHeading?heading('KPI & target','Target rencana dan realisasi disajikan terpisah, sesuai satuan setiap indikator.')+scopeTools(searchField('Cari indikator atau flagship')):'')+`<p class="quiet-note">Menampilkan target ${y}${year==='all'?' (akhir periode)':''}. Sebagian angka tahunan adalah interpolasi dari workbook, bukan target resmi yang disebut langsung di FYDP. Buka dasar target untuk rinciannya.</p>`+(kk.map(k=>{const n=attainment(k.actuals[y],k.targets[y]);return `<article class="kpi-row"><div class="kpi-top"><div><p class="eyebrow">${esc(k.category)} · ${esc(k.programs.join(' / '))}</p><h3>${esc(k.name)}</h3><p class="file-secondary">Satuan: ${esc(k.unit)}</p></div><div class="metric"><small>Target ${y}</small><strong>${formatValue(k.targets[y],k.unit)}</strong></div><div class="metric"><small>Realisasi</small><strong>${formatValue(k.actuals[y],k.unit)}</strong></div><div class="metric"><small>Capaian</small><strong>${n===null?'—':n+'%'}</strong></div></div><details><summary>Target tahunan & dasar angka</summary><div class="table-scroll"><table class="data-table"><thead><tr><th>Tahun</th><th>Target</th><th>Realisasi</th><th>Capaian</th></tr></thead><tbody>${years().map(t=>{const a=attainment(k.actuals[t],k.targets[t]);return `<tr><th>${t}</th><td>${formatValue(k.targets[t],k.unit)}</td><td>${formatValue(k.actuals[t],k.unit)}</td><td>${a===null?'—':a+'%'}</td></tr>`;}).join('')}</tbody></table></div><p class="quiet-note">${esc(k.source)}<br>${esc(k.notes)}<br>Workbook: KPI per Tahun 2025-2029, baris ${esc(k.row||'input demo')}. Target nol tidak dihitung menjadi persentase.</p></details>${role()==='admin'||(role()==='staf'&&k.programs.some(p=>canEdit(p)))?`<button class="plain-button" data-edit="kpis" data-id="${esc(k.id)}">Isi realisasi${role()==='admin'?' / ubah target':''}</button>`:''}</article>`;}).join('')||empty('Belum ada indikator','Tidak ada indikator yang sesuai filter.'));}
function renderMilestones(){return heading('Milestone periode','Tonggak tahunan adalah rencana. Status pencapaiannya diisi setelah ada bukti pelaksanaan.')+scopeTools()+`<ol class="milestone-list">${byPeriod(db.milestones).filter(m=>year==='all'||String(m.year)===year).map(m=>`<li><time>${m.year}</time><div><p>${esc(m.name)}</p>${badge(m.status)}<p class="file-secondary">PIC: ${esc(m.pic||'Belum ditetapkan')}</p>${role()==='admin'?`<button class="plain-button" data-edit="milestones" data-id="${m.id}">Perbarui milestone</button>`:''}</div></li>`).join('')}</ol>`;}
function renderDivisionPlan(){return heading('Rencana per divisi','Rencana lintas flagship, ditampilkan terpisah agar tidak dihitung ganda sebagai aktivitas flagship.')+scopeTools(searchField('Cari rencana, output, atau divisi'))+(period!==seed.periods[0].id?empty('Belum ada rencana divisi','Data divisi sumber hanya berlaku untuk FYDP 2025–2029.'):uniq(db.divisions.map(d=>d.Divisi)).map(d=>{const list=db.divisions.filter(r=>r.Divisi===d&&Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase()));return list.length?`<section class="section-space"><h2>${esc(d)}</h2>${list.map(r=>`<details class="component"><summary><div><h3>${esc(r.Aktivitas)}</h3><small>${esc(r.Durasi)} · Tahun mulai belum ditetapkan</small></div></summary><div class="activity-item"><div><p>${esc(r['Tujuan Utama'])}</p><h4>Output</h4><p>${esc(r['Key Output'])}</p><h4>Target / KPI divisi</h4><p>${esc(r['Target / KPI'])}</p></div></div></details>`).join('')}</section>`:'';}).join(''))+`<p class="quiet-note">Filter tahun tidak mempersempit rencana divisi karena sumber hanya menyebut durasi, tanpa tahun mulai.</p>`;}
function renderDivisions(){
 const tab=qs.get('tab')||'plans';
 const nav=tabs([['plans','Rencana divisi'],['monitoring','Kerangka M&E'],['capabilities','SDM & kapabilitas'],['funding','Pendanaan']],tab,'divisions');
 if(tab==='plans')return renderDivisionPlan().replace(scopeTools(searchField('Cari rencana, output, atau divisi')),scopeTools(searchField('Cari rencana, output, atau divisi'))+nav);
 const conf={monitoring:['Kerangka M&E','Komponen M&E'],capabilities:['SDM & kapabilitas','Flagship'],funding:['Rencana pendanaan','Flagship / Aset']}[tab];
 if(!conf)return renderDivisionPlan();
 const list=period===seed.periods[0].id?db[tab].filter(r=>Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase())):[];
 return heading(conf[0],'Referensi pendukung pelaksanaan FYDP. Buka rincian sesuai kebutuhan.')+scopeTools(searchField('Cari referensi pendukung'))+nav+`<p class="quiet-note">Referensi berlaku untuk seluruh periode 2025–2029; sumber tidak merinci alokasi per tahun.</p>`+(list.length?list.map(r=>`<details class="component"><summary><div><h3>${esc(r[conf[1]])}</h3><small>${esc(r['Lead Division']||r['Penanggung Jawab']||r['Kategori']||'')}</small></div></summary><div class="activity-item"><dl class="details-list">${Object.entries(r).filter(([k])=>k!==conf[1]&&k!=='No').map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></div></details>`).join(''):empty('Tidak ada referensi','Belum ada data sumber untuk pilihan ini.'));
}
function documentList(forProgram){return byPeriod(db.documents).filter(d=>(!forProgram||d.program===forProgram)&&(!docScope||(docScope==='general'?!d.program:d.program===docScope))&&(!docComponent||d.component===docComponent)&&(year==='all'||String(d.year)===year)&&(!docType||d.type===docType)&&`${d.title} ${d.filename} ${d.program} ${d.tags||''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>docSort==='az'?a.title.localeCompare(b.title,'id'):docSort==='za'?b.title.localeCompare(a.title,'id'):docSort==='oldest'?a.created.localeCompare(b.created):docSort==='date-asc'?a.date.localeCompare(b.date):docSort==='date-desc'?b.date.localeCompare(a.date):b.created.localeCompare(a.created));}
function renderLibrary(forProgram=null,withHeading=true){const docs=documentList(forProgram);return (withHeading?heading('Pustaka pengetahuan','Dokumen umum, referensi program, dan bukti pelaksanaan dalam satu tempat.',canUpload()?`<a class="button" href="${link('upload',{program:forProgram||docScope,component:docComponent})}">Unggah dokumen</a>`:''):'')+scopeTools(searchField('Cari judul, nama berkas, atau tag')+`<label>Lingkup<select id="docScope" class="field">${opt('','Semua dokumen',docScope)}${opt('general','Umum',docScope)}${byPeriod(db.programs).map(p=>opt(p.id,p.name,docScope)).join('')}</select></label>`)+`<div class="toolbar"><label>Komponen<select id="docComponent" class="field">${opt('','Semua komponen',docComponent)}${byPeriod(db.components).filter(c=>!docScope||c.program===docScope).map(c=>opt(c.id,c.name,docComponent)).join('')}</select></label><label>Jenis berkas<select id="docType" class="field">${opt('','Semua jenis',docType)}${options(['PDF','DOCX','XLSX','PNG','JPG','TXT'],docType)}</select></label><label>Urutkan<select id="docSort" class="field">${[['newest','Unggahan terbaru'],['oldest','Unggahan terlama'],['date-desc','Tanggal dokumen terbaru'],['date-asc','Tanggal dokumen terlama'],['az','Judul A–Z'],['za','Judul Z–A']].map(([v,l])=>opt(v,l,docSort)).join('')}</select></label></div><p class="result-count" role="status">${docs.length} dokumen · Berkas demo tersimpan hanya di browser ini</p>`+(docs.length?`<div class="table-scroll"><table class="data-table"><thead><tr><th>Dokumen</th><th>Lingkup / tanggal</th><th>Aksi</th></tr></thead><tbody>${docs.map(d=>`<tr><td><strong>${esc(d.title)}</strong><span class="file-secondary">${esc(d.type)} · ${esc(d.filename)}<br>${esc(d.tags||'')}</span></td><td>${esc(d.program||'Umum')}<span class="file-secondary">${esc(db.components.find(c=>c.id===d.component)?.name||'')}<br>${esc(d.date)} · Tahun ${d.year}</span></td><td><button class="plain-button" data-download="${d.id}">Unduh</button>${role()==='admin'||(role()==='staf'&&d.owner===actor.id)?`<br><button class="plain-button danger" data-delete-doc="${d.id}">Hapus</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Belum ada dokumen yang sesuai','Unggah berkas contoh untuk mencoba pencarian, filter, dan pengurutan. PDF dan Excel sumber tidak disalin ke repository.',canUpload()?`<a class="button secondary" href="${link('upload',{program:forProgram||docScope,component:docComponent})}">Unggah dokumen demo</a>`:`<a class="button secondary" href="${link('login')}">Masuk mode demo</a>`));}
function formField(name,label,value='',type='text',extra=''){return `<div class="form-group"><label for="f-${name}">${label}</label><input class="field" id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;}
function selectField(name,label,content){return `<div class="form-group"><label for="f-${name}">${label}</label><select class="field" id="f-${name}" name="${name}">${content}</select></div>`;}
function textField(name,label,value='',required=''){return `<div class="form-group span-all"><label for="f-${name}">${label}</label><textarea class="field" id="f-${name}" name="${name}" ${required}>${esc(value)}</textarea></div>`;}
function renderUpload(){if(!canUpload())return empty('Masuk mode demo terlebih dahulu','Pilih akun contoh untuk mencoba unggah dokumen.', `<a class="button" href="${link('login')}">Masuk</a>`);const ps=byPeriod(db.programs).filter(p=>role()!=='staf'||canEdit(p.id));const selected=ps.some(p=>p.id===qs.get('program'))?qs.get('program'):'';return heading('Unggah dokumen','Pilih lingkup yang tepat agar dokumen mudah ditemukan.')+`<div class="form-layout"><form id="upload-form">${formField('title','Judul dokumen','','text','required maxlength="180"')}${selectField('program','Lingkup dokumen',opt('','Pustaka umum',selected)+ps.map(p=>opt(p.id,p.name,selected)).join(''))}${selectField('component','Komponen (opsional)',opt('','Seluruh flagship','')+byPeriod(db.components).filter(c=>c.program===selected).map(c=>opt(c.id,c.name,qs.get('component'))).join(''))}<div class="form-grid">${selectField('year','Tahun rencana',options(years(),year==='all'?activePeriod().start:year))}${formField('date','Tanggal dokumen','','date','required')}</div>${formField('tags','Tag / kata kunci','','text','maxlength="200"')}${formField('file','Berkas contoh','','file','required accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg,.txt"')}<p class="form-note">Maksimum 10 MB. Gunakan berkas contoh, bukan dokumen rahasia. Berkas disimpan lokal di browser melalui IndexedDB.</p><button class="button" type="submit">Simpan dokumen demo</button> <a class="button secondary" href="${link('knowledge')}">Batal</a></form><aside class="form-aside"><h2>Dokumen yang tertata</h2><p>Pustaka umum untuk pedoman lintas program. Pilih flagship atau komponen untuk laporan, bahan kerja, dan bukti realisasinya.</p><p class="quiet-note">Unggahan ini tidak dikirim ke GitHub dan tidak dapat dilihat dari perangkat lain. Penyimpanan bersama memerlukan backend.</p></aside></div>`;}
function fileDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('seamolec-demo-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function blobStore(operation,key,blob){const d=await fileDB();try{return await new Promise((resolve,reject)=>{const t=d.transaction('files',operation==='get'?'readonly':'readwrite');const s=t.objectStore('files');const r=operation==='put'?s.put(blob,key):operation==='delete'?s.delete(key):s.get(key);let value;r.onsuccess=()=>value=r.result;t.oncomplete=()=>resolve(value);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}finally{d.close();}}
function renderLogin(){return `<div class="login-layout"><section class="login-story"><p class="eyebrow">SEAMOLEC · Monitoring program</p><h1>Rencana yang jelas.<br>Langkah yang terukur.</h1><p>Satu pintu masuk untuk staf, direktur, dan admin. Akses mengikuti peran serta program yang ditugaskan.</p><div class="source-block"><p><strong>Staf</strong> · aktivitas dan dokumen programnya.</p><p><strong>Direktur</strong> · pemantauan seluruh program.</p><p><strong>Admin</strong> · akun, periode, dan data program.</p></div><a class="text-link" href="index.html">← Kembali ke beranda</a></section><section class="login-form"><h2>Masuk ke ruang kerja</h2><form id="login-form">${formField('username','Username','','text','autocomplete="username" disabled')}${formField('password','Password','','password','autocomplete="current-password" disabled')}<button class="button" disabled>Masuk</button><p class="form-note">Login sebenarnya belum terhubung. Tidak ada pendaftaran mandiri; akun nantinya dibuat oleh admin.</p></form><div class="demo-entry"><h3>Coba alurnya</h3><p>Mode demo tidak meminta atau menyimpan password. Peran di sini hanya simulasi, bukan pembatasan akses yang aman.</p><form id="demo-form">${selectField('user','Akun demo',db.users.filter(u=>!u.disabled).map(u=>opt(u.id,`${u.name} · ${u.role}`,actor?.id||'demo-staff')).join(''))}<button class="button secondary">Buka mode demo</button></form></div></section></div>`;}
const adminSections=[['programs','Flagship'],['components','Komponen'],['activities','Aktivitas'],['kpis','KPI'],['milestones','Milestone'],['users','Akun'],['periods','Periode']];
function renderAdmin(){if(role()!=='admin')return empty('Administrasi khusus admin','Gunakan akun Admin Demo untuk mencoba pengelolaan akun dan konten.', `<a class="button" href="${link('login')}">Pilih akun demo</a>`);if(!adminSections.some(([x])=>x===adminTab))adminTab='programs';const list=['users','periods'].includes(adminTab)?db[adminTab]:byPeriod(db[adminTab]);const filtered=list.filter(x=>Object.values(x).flat().join(' ').toLowerCase().includes(search.toLowerCase())&&(!x.year||year==='all'||String(x.year)===year));return heading('Administrasi','Kelola akun, periode, struktur program, dan data pemantauan.',`<button class="button" data-edit="${adminTab}">+ Tambah ${adminSections.find(([k])=>k===adminTab)[1]}</button>`)+scopeTools(searchField('Cari data administrasi'))+tabs(adminSections,adminTab,'admin')+`<p class="quiet-note">Semua perubahan adalah simulasi lokal. Tidak ada akun atau password nyata yang dibuat, dan perubahan tidak memengaruhi data di perangkat lain.</p>`+(filtered.length?`<div class="table-scroll"><table class="data-table admin-table"><thead><tr><th>Nama / judul</th><th>Keterangan</th><th>Kelola</th></tr></thead><tbody>${filtered.map(x=>`<tr><td><strong>${esc(x.name)}</strong>${x.title?`<span class="file-secondary">${esc(x.title)}</span>`:''}</td><td>${esc(adminTab==='users'?`${x.username} · ${x.role}${x.disabled?' · Nonaktif':''}`:adminTab==='periods'?`${x.start}–${x.end}`:adminTab==='activities'?`${x.program} · ${x.year} · ${x.status}`:adminTab==='milestones'?`${x.year} · ${x.status}`:x.program||x.category||x.division||'')}</td><td><button class="plain-button" data-edit="${adminTab}" data-id="${esc(x.id)}">Edit</button>${['programs','components','activities','milestones','kpis'].includes(adminTab)?` · <button class="plain-button danger" data-delete="${adminTab}" data-id="${esc(x.id)}">Hapus</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Belum ada data','Tambahkan data pertama untuk periode ini.'))+`<div class="section-space"><button class="button secondary" data-action="export">Ekspor data demo (JSON)</button><p class="quiet-note">Ekspor tidak menyertakan berkas unggahan atau password.</p></div>`;}
function renderSources(){return heading('Sumber & catatan data','Memisahkan rencana, asumsi, dan hasil pelaksanaan.')+`<section class="source-block"><h2>Struktur yang digunakan</h2><p>FYDP 2025–2029 → 9 flagship → 42 komponen → 88 aktivitas. Ada 12 indikator tahunan, 5 milestone tahunan, serta 25 rencana divisi. Rencana divisi merupakan sudut pandang terpisah dan tidak ditambahkan ke jumlah aktivitas flagship.</p></section><section class="source-block"><h2>Dokumen sumber</h2><p>Final_SEAMOLEC FYDP.pdf (68 halaman), terutama halaman 30–44; dan Tabel_Kerja_SEAMOLEC_FYDP_2025-2029 (2).xlsx (10 sheet). Berkas asli tidak dipublikasikan bersama website.</p><p>Workbook mencantumkan sumber tambahan “One Page Seamolec FYDP.docx” yang tidak dilampirkan. Target turunannya dipertahankan sesuai workbook, dengan catatan sumber aslinya. Nama AILOS, R-MODE, dan COALA mengikuti penamaan terbaru pada sheet Panduan. PDF masih menggunakan beberapa nama generik.</p></section><section class="source-block"><h2>Target tidak sama dengan realisasi</h2><p>Seluruh realisasi KPI pada sumber masih kosong. Tanda “—” berarti belum ada data, bukan nol. Sebagian target tahunan merupakan interpolasi atau pentahapan; catatan asli tersedia pada setiap KPI. Angka persentase disimpan sebagai desimal: 0,2 ditampilkan sebagai 20%.</p><p>Capaian KPI = realisasi ÷ target × 100%. Target nol atau realisasi kosong tidak menghasilkan persentase. Capaian aktivitas = jumlah aktivitas selesai ÷ seluruh aktivitas dalam filter; hanya ditampilkan jika semua status sudah diketahui. Tidak ada rata-rata lintas KPI dengan satuan berbeda.</p></section><section class="source-block"><h2>Hal yang perlu dikonfirmasi</h2><ul><li>Lead division bersifat indikatif, mengikuti sheet Panduan.</li><li>PIC dan sebagian besar status belum ditetapkan.</li><li>Rencana divisi hanya menyebut durasi, belum tahun mulai.</li><li>Delapan aktivitas tambahan pada baris 82–89 mengikuti workbook; tidak diasumsikan telah disahkan di PDF.</li><li>Indikator bersama ditautkan ke beberapa flagship tanpa menggandakan nilainya.</li></ul></section><section class="source-block"><h2>Login dan penyimpanan</h2><p>Satu halaman login untuk semua peran, tanpa register. Mode demo memakai data lokal browser, bukan akun sungguhan. Peran dapat disimulasikan oleh siapa pun. GitHub Pages tidak melindungi data frontend.</p><p>Implementasi produksi perlu backend untuk autentikasi, pemeriksaan hak akses setiap permintaan, penyimpanan password ter-hash, unggahan privat, pencatatan perubahan, serta penugasan staf. Direktur secara default membaca seluruh data; admin mengelola akun dan struktur; staf mengubah aktivitas/KPI yang ditugaskan dan mengunggah dokumen.</p></section>`;}
function render(){const focused=document.activeElement,focusId=focused?.id,start=focused?.selectionStart;header();let content=page==='index'?renderPrograms(true):page==='programs'?renderPrograms(false):page==='program'?renderDetail():page==='kpi'?renderKpis():page==='knowledge'?renderLibrary():page==='upload'?renderUpload():page==='login'?renderLogin():page==='admin'?renderAdmin():page==='milestones'?renderMilestones():page==='divisions'?renderDivisions():renderSources();main.innerHTML=(page==='login'?'':banner())+content;if(focusId){const el=document.getElementById(focusId);el?.focus();if(typeof start==='number'&&el?.setSelectionRange)try{el.setSelectionRange(start,start);}catch{}}}
function editor(type,itemId){const original=db[type]?.find(x=>x.id===itemId);if(!db[type]||(!original&&role()!=='admin'))return;if(role()!=='admin'&&!(type==='activities'&&canEdit(original.program))&&!(type==='kpis'&&original.programs.some(canEdit)))return;const x=original||{},admin=role()==='admin';let fields='';const ps=byPeriod(db.programs),cs=byPeriod(db.components);const prog=(selected)=>selectField('program','Flagship',ps.map(p=>opt(p.id,p.name,selected)).join(''));const stat=()=>selectField('status','Status',options(statuses,x.status||'Belum ada data'));const name=()=>formField('name',type==='users'?'Nama tampilan':'Nama / judul',x.name,'text','required maxlength="400"');
if(type==='programs')fields=name()+formField('title','Kepanjangan / deskripsi singkat',x.title,'text','required maxlength="400"')+formField('cluster','Klaster strategi',x.cluster,'text','required')+formField('strategy','Kode strategi',x.strategy,'text','required')+selectField('division','Lead division',options(['CPMP','IT&KM','Training','R&D','Admin & Finance'],x.division))+formField('team','Pemilik / tim',x.team);
if(type==='components')fields=name()+prog(x.program);
if(type==='activities')fields=(admin?name()+prog(x.program)+selectField('component','Komponen',cs.filter(c=>c.program===(x.program||ps[0]?.id)).map(c=>opt(c.id,c.name,x.component)).join(''))+formField('code','Kode aktivitas',x.code)+selectField('year','Tahun rencana',options(years(),x.year||activePeriod().start))+formField('division','Divisi pelaksana',x.division,'text','required'):`<p class="span-all">${esc(x.name)}</p>`)+formField('pic','PIC',x.pic)+stat()+textField('notes','Catatan / referensi bukti',x.notes);
if(type==='milestones')fields=textField('name','Tonggak implementasi',x.name,'required')+selectField('year','Tahun rencana',options(years(),x.year||activePeriod().start))+formField('pic','PIC / koordinator',x.pic)+stat()+textField('notes','Catatan',x.notes);
if(type==='periods')fields=name()+formField('start','Tahun mulai',x.start||2030,'number','required min="2000" max="2100"')+formField('end','Tahun akhir',x.end||2034,'number','required min="2000" max="2100"')+'<p class="form-note span-all">Periode baru dimulai kosong. Batas periode yang sudah berisi data tidak dapat diubah.</p>';
if(type==='users')fields=name()+formField('username','Username demo',x.username,'text','required pattern="[a-zA-Z0-9._-]{3,40}" maxlength="40"')+selectField('role','Peran',options(['staf','direktur','admin'],x.role||'staf'))+selectField('disabled','Status akun',opt('false','Aktif',String(!!x.disabled))+opt('true','Nonaktif',String(!!x.disabled)))+`<div class="form-group span-all"><label>Penugasan flagship (untuk staf)</label><div class="check-list">${db.programs.map(p=>`<label><input type="checkbox" name="programs" value="${esc(p.id)}" ${(x.programs||[]).includes(p.id)?'checked':''}> ${esc(p.name)} · ${esc(db.periods.find(t=>t.id===p.period)?.name)}</label>`).join('')}</div></div>`+formField('password','Password akun (tersedia setelah backend terhubung)','','password','disabled autocomplete="new-password"')+'<p class="form-note span-all">Prototipe hanya menyimpan nama, username, peran, dan penugasan. Akun muncul di pilihan demo, bukan sebagai kredensial login.</p>';
if(type==='kpis'){fields=(admin?name()+formField('category','Kategori',x.category,'text','required')+formField('unit','Satuan (awali % untuk persentase)',x.unit,'text','required')+`<div class="form-group span-all"><label>Flagship terkait</label><div class="check-list">${ps.map(p=>`<label><input type="checkbox" name="programs" value="${esc(p.id)}" ${(x.programs||[]).includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('')}</div></div>`:`<p class="span-all">${esc(x.name)} · ${esc(x.unit)}</p>`)+`<p class="form-note span-all">Untuk satuan persen, isi angka persen: ketik 20 untuk 20%. Kosong berarti belum ada data; nol adalah nilai yang sudah diketahui. Capaian dihitung otomatis.</p>`+years().map(y=>{const percent=(x.unit||'').startsWith('%');const value=v=>v===null||v===undefined?'':percent?Number((v*100).toFixed(5)):v;return (admin?formField('target-'+y,'Target '+y,value(x.targets?.[y]),'number','min="0" step="any"'):'')+formField('actual-'+y,'Realisasi '+y,value(x.actuals?.[y]),'number','min="0" step="any"');}).join('')+(admin?textField('source','Sumber target / status pengesahan',x.source,'required')+textField('notes','Dasar target / interpolasi',x.notes,'required'):'');}
let dlg=document.querySelector('#editor-dialog');if(!dlg){dlg=document.createElement('dialog');dlg.id='editor-dialog';document.body.append(dlg);}dlg.innerHTML=`<div class="heading"><h2>${original?'Perbarui':'Tambah'} ${esc(adminSections.find(([k])=>k===type)?.[1]||type)}</h2><button class="button secondary small" type="button" data-close>Tutup</button></div><form id="editor-form" data-type="${type}" data-id="${esc(itemId||'')}"><div class="form-grid">${fields}</div><p id="editor-error" role="alert" class="danger"></p><div class="actions"><button class="button">Simpan perubahan demo</button><button class="button secondary" type="button" data-close>Batal</button></div></form>`;dlg.showModal();}
function saveEditor(form){const type=form.dataset.type,old=db[type].find(x=>x.id===form.dataset.id),f=new FormData(form),admin=role()==='admin';if(!admin&&!(old&&((type==='activities'&&canEdit(old.program))||(type==='kpis'&&old.programs.some(canEdit)))))throw Error('Peran demo tidak memiliki akses untuk perubahan ini.');const x=structuredClone(old||{id:id(),period});const v=n=>String(f.get(n)||'').trim();const take=names=>names.forEach(n=>x[n]=v(n));if(['programs','components','periods','users'].includes(type))take(['name']);
if(type==='programs')take(['title','cluster','strategy','division','team']);
if(type==='components'){take(['program']);if(old&&x.program!==old.program&&db.activities.some(a=>a.component===old.id))throw Error('Komponen yang sudah berisi aktivitas tidak dapat dipindahkan ke flagship lain.');}
if(type==='activities'){if(admin){take(['name','program','component','code','division']);x.year=Number(v('year'));if(!db.components.some(c=>c.id===x.component&&c.program===x.program))throw Error('Pilih komponen yang sesuai dengan flagship.');}take(['pic','status','notes']);}
if(type==='milestones'){take(['name','pic','status','notes']);x.year=Number(v('year'));}
if(type==='periods'){x.start=Number(v('start'));x.end=Number(v('end'));if(x.end<x.start||x.end-x.start>20)throw Error('Rentang periode harus 1–21 tahun dan tahun akhir tidak boleh lebih kecil.');if(old&&(x.start!==old.start||x.end!==old.end)&&['programs','kpis','activities','milestones','documents'].some(t=>db[t].some(a=>a.period===old.id)))throw Error('Periode sudah berisi data. Buat periode baru untuk rentang tahun berbeda.');if(db.periods.some(p=>p.id!==x.id&&p.start===x.start&&p.end===x.end))throw Error('Rentang periode tersebut sudah ada.');delete x.period;}
if(type==='users'){take(['username','role']);x.disabled=v('disabled')==='true';x.programs=f.getAll('programs');if(db.users.some(u=>u.id!==x.id&&u.username.toLowerCase()===x.username.toLowerCase()))throw Error('Username sudah digunakan.');if(x.id===actor.id&&(x.disabled||x.role!=='admin'))throw Error('Akun admin yang sedang digunakan tidak dapat menonaktifkan atau menurunkan perannya sendiri.');delete x.period;}
if(type==='kpis'){if(admin){take(['name','category','unit','source','notes']);x.programs=f.getAll('programs');if(!x.programs.length)throw Error('Pilih minimal satu flagship.');}const percent=x.unit.startsWith('%');x.targets=x.targets||{};x.actuals=x.actuals||{};for(const y of years()){const parse=n=>v(n)===''?null:Number(v(n))/(percent?100:1);if(admin)x.targets[y]=parse('target-'+y);x.actuals[y]=parse('actual-'+y);}}
if(old)db[type][db[type].indexOf(old)]=x;else db[type].push(x);if(type==='users')actor=db.users.find(u=>u.id===actor.id);const persisted=save();document.querySelector('#editor-dialog').close();render();if(persisted)toast('Perubahan demo tersimpan di browser ini.');}
function deleteItem(type,itemId){if(role()!=='admin')return;const x=db[type].find(x=>x.id===itemId);if(!x)return;if(type==='programs'&&['components','activities','documents','kpis'].some(t=>db[t].some(r=>r.program===itemId||r.programs?.includes(itemId))))return toast('Flagship masih memiliki komponen, aktivitas, KPI, atau dokumen. Hapus atau pindahkan data terkait terlebih dahulu.');if(type==='components'&&['activities','documents'].some(t=>db[t].some(r=>r.component===itemId)))return toast('Komponen masih memiliki aktivitas atau dokumen. Hapus atau pindahkan data terkait terlebih dahulu.');if(!confirm(`Hapus “${x.name}” dari data demo browser ini?`))return;db[type]=db[type].filter(r=>r.id!==itemId);save();render();toast('Data demo dihapus.');}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;currentPage=1;render();}});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='period'){period=el.value;year='all';docScope='';docComponent='';currentPage=1;if(page==='program'){location.href=link('programs');return;}render();return;}const setters={year:v=>year=v,division:v=>division=v,status:v=>status=v,docScope:v=>{docScope=v;docComponent='';},docComponent:v=>docComponent=v,docType:v=>docType=v,docSort:v=>docSort=v};if(setters[el.id]){setters[el.id](el.value);currentPage=1;render();return;}if(el.name==='program'){const select=el.closest('form')?.querySelector('[name=component]');if(select)select.innerHTML=(el.closest('#upload-form')?opt('','Seluruh flagship',''):'')+byPeriod(db.components).filter(c=>c.program===el.value).map(c=>opt(c.id,c.name,'')).join('');}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){currentPage=Number(b.dataset.page);render();return;}if(b.dataset.edit){editor(b.dataset.edit,b.dataset.id);return;}if(b.hasAttribute('data-close')){b.closest('dialog').close();return;}if(b.dataset.delete){deleteItem(b.dataset.delete,b.dataset.id);return;}if(b.dataset.action==='logout'){actor=null;try{sessionStorage.removeItem('seamolec-actor');}catch{}render();return;}if(b.dataset.action==='export'&&role()==='admin'){downloadBlob(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),'seamolec-demo.json');return;}if(b.dataset.download){const d=db.documents.find(d=>d.id===b.dataset.download);try{const blob=await blobStore('get',d.id);if(!blob)throw Error();downloadBlob(blob,d.filename);}catch{toast('Berkas lokal tidak tersedia. Unggah ulang berkas pada browser ini.');}return;}if(b.dataset.deleteDoc){const d=db.documents.find(d=>d.id===b.dataset.deleteDoc);if(!d||!(role()==='admin'||(role()==='staf'&&d.owner===actor.id)))return;if(!confirm(`Hapus dokumen demo “${d.title}”?`))return;try{await blobStore('delete',d.id);db.documents=db.documents.filter(x=>x.id!==d.id);save();render();}catch{toast('Dokumen belum berhasil dihapus. Coba kembali.');}}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(form.id==='demo-form'){actor=db.users.find(u=>u.id===new FormData(form).get('user')&&!u.disabled);if(!actor)return;try{sessionStorage.setItem('seamolec-actor',actor.id);}catch{toast('Penyimpanan sesi tidak tersedia. Izinkan penyimpanan browser untuk mencoba mode demo.');return;}location.href=link(role()==='admin'?'admin':'index');return;}if(form.id==='editor-form'){try{saveEditor(form);}catch(err){document.querySelector('#editor-error').textContent=err.message;}return;}if(form.id==='upload-form'){if(!canUpload())return;const f=new FormData(form),file=f.get('file'),ext=file.name.split('.').pop().toUpperCase();if(!['PDF','DOCX','XLSX','PNG','JPG','JPEG','TXT'].includes(ext)||file.size>10*1024*1024||file.size===0)return toast('Gunakan berkas PDF, DOCX, XLSX, PNG, JPG, atau TXT berukuran 1 byte–10 MB.');const program=String(f.get('program'));if(role()==='staf'&&program&&!canEdit(program))return toast('Program tidak termasuk penugasan akun demo ini.');const component=String(f.get('component'));if(component&&!db.components.some(c=>c.id===component&&c.program===program))return toast('Komponen tidak sesuai dengan flagship.');const doc={id:id(),period,title:String(f.get('title')).trim(),program,component,year:Number(f.get('year')),date:String(f.get('date')),tags:String(f.get('tags')).trim(),type:ext==='JPEG'?'JPG':ext,filename:file.name,created:new Date().toISOString(),owner:actor.id};const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await blobStore('put',doc.id,file);db.documents.push(doc);if(!save()){db.documents.pop();await blobStore('delete',doc.id);return;}location.href=link('knowledge',{program});}catch{toast('Penyimpanan berkas gagal. Pastikan penyimpanan browser tersedia dan ruang cukup.');}finally{submit.disabled=false;}}});
render();
