// Run with node --test. Tests use an isolated JavaScript VM, not a browser or user storage.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
function fixture(){
 const node={innerHTML:'',textContent:'',close(){},querySelectorAll(){return []}};
 const context=vm.createContext({window:{},document:{querySelector:()=>node,querySelectorAll:()=>[],addEventListener(){}},location:{pathname:'/index.html',search:''},localStorage:{getItem:()=>null,setItem(){}},sessionStorage:{getItem:()=>null},structuredClone,URLSearchParams,Intl,crypto:require('node:crypto').webcrypto,setTimeout:()=>0,clearTimeout(){},confirm:()=>true,FormData:class{constructor(form){this.data=form.values;}get(k){return this.data[k]??null;}getAll(k){return [].concat(this.data[k]||[]);}}});
 vm.runInContext(fs.readFileSync(path.join(root,'data.js'),'utf8'),context);
 vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/render\(\);\s*$/,''),context);
 return code=>vm.runInContext(code,context);
}
test('Source counts, relations and unknown actuals are preserved',()=>{const run=fixture();assert.equal(run('db.programs.length'),9);assert.equal(run('db.components.length'),42);assert.equal(run('db.activities.length'),88);assert.equal(run('db.kpis.length'),12);assert.equal(run('db.divisions.length'),25);assert.equal(run('db.activities.every(a=>db.components.some(c=>c.id===a.component&&c.program===a.program))'),true);assert.equal(run('db.kpis.every(k=>Object.values(k.actuals).every(v=>v===null))'),true);assert.equal(run('db.activities.filter(a=>a.status==="Belum ada data").length'),80);});
test('Search combines nested components, year and division',()=>{const r=fixture();assert.equal(r('search="Maluku";programList().length'),1);assert.equal(r('year="2029";programList().length'),0);assert.equal(r('search="";year="all";division="Training";programList().length'),4);assert.equal(r('division="";search="zzzz";programList().length'),0);});
test('Progress keeps unknown distinct from zero and handles zero targets',()=>{const r=fixture();assert.equal(r('completion(activitiesFor("AILOS"))'),null);assert.equal(r('completion([{status:"Selesai"},{status:"Belum mulai"}])'),50);assert.equal(r('completion([])'),null);assert.equal(r('attainment(null,10)'),null);assert.equal(r('attainment(1,0)'),null);assert.equal(r('attainment(0,10)'),0);assert.equal(r('attainment(12,10)'),120);assert.equal(r('formatValue(0.2,"% kenaikan")'),'20%');});
test('Six document orders, search and scope filters',()=>{const r=fixture();r(`db.documents=[{id:'1',period,title:'Zebra',filename:'z.pdf',type:'PDF',program:'AILOS',component:'component-1',year:2026,date:'2025-02-01',created:'2026-03-01'},{id:'2',period,title:'Alpha',filename:'a.docx',type:'DOCX',program:'',component:'',year:2025,date:'2026-01-01',created:'2026-02-01'}]`);for(const [sort,first]of [['newest','1'],['oldest','2'],['az','2'],['za','1'],['date-asc','1'],['date-desc','2']])assert.equal(r(`docSort='${sort}';documentList()[0].id`),first);assert.equal(r('docScope="general";documentList().length'),1);assert.equal(r('docScope="";docType="PDF";documentList()[0].id'),'1');assert.equal(r('docType="";search="alpha";documentList()[0].id'),'2');assert.equal(r('search="";year="2029";documentList().length'),0);});
test('Simulated roles constrain edit and upload controls',()=>{const r=fixture();assert.equal(r('canEdit("AILOS")'),false);assert.equal(r('actor=db.users.find(u=>u.role==="staf");canEdit("AILOS")'),true);assert.equal(r('canEdit("CODEA")'),false);assert.equal(r('actor=db.users.find(u=>u.role==="direktur");canEdit("AILOS")'),false);assert.equal(r('canUpload()'),false);assert.equal(r('actor=db.users.find(u=>u.role==="admin");canEdit("CODEA")'),true);});
test('Editor persists percentage as decimal, blank as null, zero as actual',()=>{const r=fixture();r(`actor=db.users[0];saveEditor({dataset:{type:'kpis',id:'kpi-2'},values:{name:'Test',category:'WT3',unit:'% kenaikan',programs:['CREATE'],source:'Test',notes:'Test','target-2029':'20','actual-2029':'10','actual-2025':'0'}})`);assert.equal(r('db.kpis[1].targets[2029]'),0.2);assert.equal(r('db.kpis[1].actuals[2029]'),0.1);assert.equal(r('db.kpis[1].actuals[2025]'),0);assert.equal(r('db.kpis[1].actuals[2026]'),null);});
test('Duplicate username, self-demotion and dependency deletion are blocked',()=>{const r=fixture();r('actor=db.users[0]');assert.throws(()=>r(`saveEditor({dataset:{type:'users'},values:{name:'Test',username:'ADMIN.DEMO',role:'staf'}})`),/Username/);assert.throws(()=>r(`saveEditor({dataset:{type:'users',id:'demo-admin'},values:{name:'Admin',username:'admin.demo',role:'staf'}})`),/sendiri/);r('deleteItem("programs","AILOS")');assert.equal(r('db.programs.length'),9);r('deleteItem("components","component-1")');assert.equal(r('db.components.length'),42);});
test('New period is empty and existing populated range cannot change',()=>{const r=fixture();r(`actor=db.users[0];saveEditor({dataset:{type:'periods'},values:{name:'FYDP 2030–2034',start:'2030',end:'2034'}})`);assert.equal(r('db.periods.length'),2);assert.throws(()=>r(`saveEditor({dataset:{type:'periods',id:'fydp-2025-2029'},values:{name:'FYDP',start:'2024',end:'2029'}})`),/sudah berisi/);assert.equal(r('period=db.periods[1].id;byPeriod(db.programs).length'),0);});
test('User-provided text is escaped and renderers do not crash',()=>{const r=fixture();assert.equal(r('esc("<script>&")'),'&lt;script&gt;&amp;');for(const expr of ['renderPrograms(true)','renderPrograms(false)','renderDetail()','renderKpis()','renderMilestones()','renderDivisions()','renderLibrary()','renderUpload()','renderLogin()','renderAdmin()','renderSources()'])assert.equal(typeof r(expr),'string');r('actor=db.users[0]');assert.equal(typeof r('renderAdmin()'),'string');assert.equal(typeof r('renderUpload()'),'string');});
test('No passwords in demo data and no raw attached documents in repository',()=>{const r=fixture();assert.equal(r('db.users.some(u=>Object.keys(u).some(k=>/password/i.test(k)))'),false);assert.equal(fs.readdirSync(root).some(f=>/\.(pdf|xlsx)$/i.test(f)),false);});

